import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import localFont from '@next/font/local'

//define and import fonts there create a local font object 
const porter = localFont({
  src: [
    {
      path: '../../public/porter-sans-inline-block.otf',
      weight: '400'
    }
    
  ],
  variable: '--font-porter'
})

const friz = localFont({
  src: [
    {
      path: '../../public/Friz-Quadrata-Std-Medium.otf',
      weight: '400'
    }
    
  ],
  variable: '--font-friz'
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={`${porter.variable} font-sans ${friz.variable}`}>{children}</body>
    </html>
  )
}
